// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://elrofncgydzlvixekjxj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVscm9mbmNneWR6bHZpeGVranhqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjI5Mzc3MDIsImV4cCI6MjA3ODUxMzcwMn0.kBf8YdXZn3cH9x-OXY0JXcP8SY03LQ_PiZpKSWT6QqQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});